In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [57]:
drugdeath = pd.read_csv("Merged_table_of_deathsbydrug_and_region.csv", header = [0,1])
drugdeath.head()

,Unnamed: 0_level_0,Year,2013,2014,2015,2016,2013,2014,2015,2016,2013,2014,2015,2016,2013,2014,2015,2016
,Region,States,"2013.Nat.Semisynth(oxy, hydrocodone)","2014.Nat.Semisynth(oxy, hydrocodone)","2015.Nat.Semisynth(oxy, hydrocodone)","2016.Nat.Semisynth(oxy, hydrocodone)","2013.Synth nonMethadone(fentanyl,tramadol)","2014Synth nonMethadone(fentanyl,tramadol)","2015.Synth nonMethadone(fentanyl,tramadol)","2016.Synth nonMethadone(fentanyl,tramadol)",2013.Methadone,2014.Methadone,2015.Methadone,2015.Methadone,2013.Heroin,2014.Heroin,2015.Heroin,2016.Heroin
0,Southeast,Alabama,65,90,87,94,30,47,70,157,41,44,40,34,40,122,111,126
1,Pacific West:,Alaska,38,40,51,45,12,14,14,0,0,12,10,13,24,25,37,49
2,Pacific West:,Arizona,253,290,298,326,52,57,72,123,64,62,75,75,146,197,247,299
3,Southeast,Arkansas,111,119,144,114,31,32,44,38,42,29,37,32,0,0,0,13
4,Pacific West:,California,1039,1047,1019,955,176,194,229,355,343,337,291,281,486,561,593,587

In [58]:
c = drugdeath.columns

In [59]:
c

MultiIndex(levels=[['2013', '2014', '2015', '2016', 'Unnamed: 0_level_0', 'Year'], ['2013.Heroin', '2013.Methadone', '2013.Nat.Semisynth(oxy, hydrocodone)', '2013.Synth nonMethadone(fentanyl,tramadol)', '2014.Heroin', '2014.Methadone', '2014.Nat.Semisynth(oxy, hydrocodone)', '2014Synth nonMethadone(fentanyl,tramadol)', '2015.Heroin', '2015.Methadone', '2015.Nat.Semisynth(oxy, hydrocodone)', '2015.Synth nonMethadone(fentanyl,tramadol)', '2016.Heroin', '2016.Nat.Semisynth(oxy, hydrocodone)', '2016.Synth nonMethadone(fentanyl,tramadol)', 'Region', 'States']],
           codes=[[4, 5, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3], [15, 16, 2, 6, 10, 13, 3, 7, 11, 14, 1, 5, 9, 9, 0, 4, 8, 12]])

In [60]:
drugdeath.columns = drugdeath.columns.droplevel(0)

In [69]:
dd = drugdeath
dd

,Region,States,"2013.Nat.Semisynth(oxy, hydrocodone)","2014.Nat.Semisynth(oxy, hydrocodone)","2015.Nat.Semisynth(oxy, hydrocodone)","2016.Nat.Semisynth(oxy, hydrocodone)","2013.Synth(fentanyl,tramadol)","2014.Synth(fentanyl,tramadol)","2015.Synth(fentanyl,tramadol)","2016.Synth(fentanyl,tramadol)",2013.Methadone,2014.Methadone,2015.Methadone,2015.Methadone,2013.Heroin,2014.Heroin,2015.Heroin,2016.Heroin
0,Southeast,Alabama,65,90,87,94,30,47,70,157,41,44,40,34,40,122,111,126
1,Pacific West:,Alaska,38,40,51,45,12,14,14,0,0,12,10,13,24,25,37,49
2,Pacific West:,Arizona,253,290,298,326,52,57,72,123,64,62,75,75,146,197,247,299
3,Southeast,Arkansas,111,119,144,114,31,32,44,38,42,29,37,32,0,0,0,13
4,Pacific West:,California,1039,1047,1019,955,176,194,229,355,343,337,291,281,486,561,593,587
5,Plains Region,Colorado,221,259,259,212,67,80,64,72,41,51,34,58,120,156,159,234
6,Northeast,Connecticut,144,157,183,206,53,94,211,500,49,50,72,72,227,299,390,450
7,Northeast,Delaware,35,38,36,31,22,29,38,79,21,24,14,11,39,54,64,56
8,Northeast,District of Columbia,10,19,21,52,0,13,26,129,0,0,0,21,35,37,67,122
9,Southeast,Florida,751,697,789,1030,200,343,610,1566,271,227,210,203,181,344,567,669
10,Southeast,Georgia,309,388,435,455,80,174,284,277,110,124,115,115,67,153,222,226
11,Pacific West:,Hawaii,39,35,37,44,0,0,13,0,17,10,0,15,10,12,15,20
12,Pacific West:,Idaho,51,42,51,64,14,13,16,20,11,18,12,15,0,11,16,25
13,Midwest,Illinois,185,253,271,378,87,127,278,907,92,106,99,123,583,711,844,1040
14,Midwest,Indiana,111,149,146,231,34,83,120,304,34,37,36,34,160,173,240,297
15,Midwest,Iowa,106,81,75,82,32,29,44,58,24,16,24,13,31,37,45,47
16,Plains Region,Kansas,88,91,74,83,37,39,36,27,30,34,26,10,12,19,21,32
17,Midwest,Kentucky,349,344,382,403,76,179,323,465,70,59,60,48,215,228,310,311
18,Southeast,Louisiana,86,93,108,111,26,29,38,89,20,20,16,16,121,107,126,149
19,Northeast,Maine,64,80,102,132,23,62,116,199,34,29,36,37,16,38,52,55
20,Northeast,Maryland,304,388,398,666,93,230,357,1091,138,153,182,197,217,313,405,650
21,Northeast,Massachusetts,179,178,225,267,98,453,949,1550,94,88,82,95,288,469,634,630
22,Midwest,Michigan,283,328,380,560,86,178,457,921,163,146,171,149,421,525,646,727
23,Midwest,Minnesota,111,102,125,137,33,44,55,99,76,81,55,67,92,100,115,149
24,Southeast,Mississippi,55,63,73,97,24,24,35,45,12,0,12,0,10,23,38,33
25,Midwest,Missouri,237,237,237,231,97,109,183,441,54,53,62,41,261,334,303,380
26,Plains Region,Montana,43,22,26,12,0,14,0,14,14,16,0,0,0,0,0,0
27,Plains Region,Nebraska,33,30,30,22,0,13,13,13,0,0,12,0,0,0,0,0
28,Pacific West:,Nevada,242,224,259,235,26,32,32,53,70,64,57,53,48,64,82,86
29,Northeast,New Hampshire,62,81,63,69,30,151,285,363,14,29,25,29,67,98,78,34
30,Northeast,New Jersey,231,245,237,346,57,111,243,689,67,50,55,84,383,424,508,850
31,Plains Region,New Mexico,209,223,160,153,23,66,42,78,28,45,33,41,89,139,156,161
32,Northeast,New York,644,608,705,892,210,294,668,1641,274,231,246,289,666,825,1058,1307
33,Southeast,North Carolina,397,462,554,611,116,217,300,601,164,131,108,118,189,266,393,544
34,Plains Region,North Dakota,0,17,15,17,0,10,0,15,0,0,0,0,0,0,0,12
35,Midwest,Ohio,518,618,690,785,167,590,1234,2296,116,107,109,96,998,1208,1444,1478
36,Plains Region,Oklahoma,375,370,277,285,88,73,93,98,68,67,62,46,22,26,36,53
37,Pacific West:,Oregon,119,137,150,128,27,33,34,43,66,59,70,46,103,124,102,114
38,Northeast,Pennsylvania,406,411,460,634,108,217,429,1309,82,81,89,113,409,503,663,926
39,Northeast,Rhode Island,80,70,95,89,32,82,137,182,28,24,30,29,65,66,45,25
40,Southeast,South Carolina,144,319,322,342,50,110,161,237,50,77,57,56,32,64,100,115
41,Plains Region,South Dakota,27,20,10,25,0,0,0,10,0,0,0,0,0,0,0,0
42,Southeast,Tennessee,524,554,643,679,99,132,251,395,86,71,67,83,68,148,205,260
43,Plains Region,Texas,452,471,473,501,112,157,186,250,128,116,144,139,369,425,523,530
44,Pacific West:,Utah,358,367,357,322,58,68,62,72,59,47,45,40,122,110,127,166
45,Northeast,Vermont,37,21,25,23,17,21,33,53,14,0,0,13,20,33,33,45
46,Northeast,Virginia,297,323,276,343,125,176,270,648,96,105,67,77,206,253,353,450
47,Pacific West:,Washington,269,288,261,292,59,62,65,93,156,115,111,122,205,289,303,283
48,Northeast,West Virginia,341,363,356,322,98,122,217,435,54,35,29,27,144,163,194,235
49,Midwest,Wisconsin,277,279,249,328,81,90,112,288,76,78,73,67,232,270,287,389
50,Plains Region,Wyoming,33,28,28,26,0,12,0,0,0,0,0,0,0,10,0,0

In [64]:
dd.columns = ['Region', 'States', '2013.Nat.Semisynth(oxy, hydrocodone)',
       '2014.Nat.Semisynth(oxy, hydrocodone)',
       '2015.Nat.Semisynth(oxy, hydrocodone)',
       '2016.Nat.Semisynth(oxy, hydrocodone)',
       '2013.Synth(fentanyl,tramadol)',
       '2014.Synth(fentanyl,tramadol)',
       '2015.Synth(fentanyl,tramadol)',
       '2016.Synth(fentanyl,tramadol)', '2013.Methadone',
       '2014.Methadone', '2015.Methadone', '2015.Methadone', '2013.Heroin',
       '2014.Heroin', '2015.Heroin', '2016.Heroin']

In [66]:
meth = dd.filter(regex="Meth")

synth = dd.filter(regex="synth")

heroin = dd.filter(regex="heroin")
nat = dd.filter(regex="nat")

In [67]:
meth

    2013.Methadone  2014.Methadone  2015.Methadone  2015.Methadone
0               41              44              40              34
1                0              12              10              13
2               64              62              75              75
3               42              29              37              32
4              343             337             291             281
5               41              51              34              58
6               49              50              72              72
7               21              24              14              11
8                0               0               0              21
9              271             227             210             203
10             110             124             115             115
11              17              10               0              15
12              11              18              12              15
13              92             106              99             123
14              34              37              36              34
15              24              16              24              13
16              30              34              26              10
17              70              59              60              48
18              20              20              16              16
19              34              29              36              37
20             138             153             182             197
21              94              88              82              95
22             163             146             171             149
23              76              81              55              67
24              12               0              12               0
25              54              53              62              41
26              14              16               0               0
27               0               0              12               0
28              70              64              57              53
29              14              29              25              29
30              67              50              55              84
31              28              45              33              41
32             274             231             246             289
33             164             131             108             118
34               0               0               0               0
35             116             107             109              96
36              68              67              62              46
37              66              59              70              46
38              82              81              89             113
39              28              24              30              29
40              50              77              57              56
41               0               0               0               0
42              86              71              67              83
43             128             116             144             139
44              59              47              45              40
45              14               0               0              13
46              96             105              67              77
47             156             115             111             122
48              54              35              29              27
49              76              78              73              67
50               0               0               0               0

In [8]:
drugdeath.stack().reset_index

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51 entries, 0 to 50
Data columns (total 18 columns):
(Unnamed: 0_level_0, Region)                          51 non-null object
(Year, States)                                        51 non-null object
(2013, 2013.Nat.Semisynth(oxy, hydrocodone))          51 non-null int64
(2014, 2014.Nat.Semisynth(oxy, hydrocodone))          51 non-null int64
(2015, 2015.Nat.Semisynth(oxy, hydrocodone))          51 non-null int64
(2016, 2016.Nat.Semisynth(oxy, hydrocodone))          51 non-null int64
(2013, 2013.Synth nonMethadone(fentanyl,tramadol))    51 non-null int64
(2014, 2014Synth nonMethadone(fentanyl,tramadol))     51 non-null int64
(2015, 2015.Synth nonMethadone(fentanyl,tramadol))    51 non-null int64
(2016, 2016.Synth nonMethadone(fentanyl,tramadol))    51 non-null int64
(2013, 2013.Methadone)                                51 non-null int64
(2014, 2014.Methadone)                                51 non-null int64
(2015, 2015.Methadone)                                51 non-null int64
(2016, 2015.Methadone)                                51 non-null int64
(2013, 2013.Heroin)                                   51 non-null int64
(2014, 2014.Heroin)                                   51 non-null int64
(2015, 2015.Heroin)                                   51 non-null int64
(2016, 2016.Heroin)                                   51 non-null int64
dtypes: int64(16), object(2)
memory usage: 7.2+ KB

In [13]:
#First group whole df by drug
deathbyreg = drugdeath.groupby(by = [("Unnamed: 0_level_0", "Region")]).sum()
deathbyreg.head()

,2013,2014,2015,2016,2013,2014,2015,2016,2013,2014,2015,2016,2013,2014,2015,2016
,"2013.Nat.Semisynth(oxy, hydrocodone)","2014.Nat.Semisynth(oxy, hydrocodone)","2015.Nat.Semisynth(oxy, hydrocodone)","2016.Nat.Semisynth(oxy, hydrocodone)","2013.Synth nonMethadone(fentanyl,tramadol)","2014Synth nonMethadone(fentanyl,tramadol)","2015.Synth nonMethadone(fentanyl,tramadol)","2016.Synth nonMethadone(fentanyl,tramadol)",2013.Methadone,2014.Methadone,2015.Methadone,2015.Methadone,2013.Heroin,2014.Heroin,2015.Heroin,2016.Heroin
"(Unnamed: 0_level_0, Region)",,,,,,,,,,,,,,,,
Midwest,2177,2391,2555,3135,693,1429,2806,5779,705,683,689,638,2993,3586,4234,4818
Northeast,2834,2982,3182,4072,966,2055,3979,8868,965,899,927,1094,2782,3575,4544,5835
Pacific West:,2408,2470,2483,2411,424,473,537,759,786,724,671,660,1144,1393,1522,1629
Plains Region,1481,1531,1352,1336,327,464,434,577,309,329,311,294,612,775,895,1022
Southeast,2442,2785,3155,3533,656,1108,1793,3405,796,723,662,657,708,1227,1762,2135

In [14]:
deathbyreg_df = pd.DataFrame(deathbyreg)
deathbyreg

,2013,2014,2015,2016,2013,2014,2015,2016,2013,2014,2015,2016,2013,2014,2015,2016
,"2013.Nat.Semisynth(oxy, hydrocodone)","2014.Nat.Semisynth(oxy, hydrocodone)","2015.Nat.Semisynth(oxy, hydrocodone)","2016.Nat.Semisynth(oxy, hydrocodone)","2013.Synth nonMethadone(fentanyl,tramadol)","2014Synth nonMethadone(fentanyl,tramadol)","2015.Synth nonMethadone(fentanyl,tramadol)","2016.Synth nonMethadone(fentanyl,tramadol)",2013.Methadone,2014.Methadone,2015.Methadone,2015.Methadone,2013.Heroin,2014.Heroin,2015.Heroin,2016.Heroin
"(Unnamed: 0_level_0, Region)",,,,,,,,,,,,,,,,
Midwest,2177,2391,2555,3135,693,1429,2806,5779,705,683,689,638,2993,3586,4234,4818
Northeast,2834,2982,3182,4072,966,2055,3979,8868,965,899,927,1094,2782,3575,4544,5835
Pacific West:,2408,2470,2483,2411,424,473,537,759,786,724,671,660,1144,1393,1522,1629
Plains Region,1481,1531,1352,1336,327,464,434,577,309,329,311,294,612,775,895,1022
Southeast,2442,2785,3155,3533,656,1108,1793,3405,796,723,662,657,708,1227,1762,2135

In [17]:
deathbyreg_munge =deathbyreg_df.pivot(index='',columns='Region')

KeyError: ''